# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0018_auto_20171219_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='dinosaurs.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.AddField(
            model_name='note',
            name='hashtags',
            field=models.ManyToManyField(to='dinosaurs.Hashtag'),
        ),
    ]
