# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0020_auto_20180113_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
